/*
 * Hans varekatalog, hentet fra billigskadedyr.dk 2026-09-07 via WooCommerce
 * Store API. Navne, priser, varenumre, lagerstatus og de korte beskrivelser
 * er hans egne, ordret. Billederne ligger i public/shop.
 *
 * To felter er tilføjet her og er IKKE hans data:
 *   pest  hvilket skadedyr varen er til, i kundens ord
 *   form  hvad slags produkt det er
 * De findes, fordi hans egne 72 kategorier blander skadedyr, mærke og
 * virkemåde i én flad liste. "Mærker" alene rummer 77 varer, "Monitorering"
 * optræder to gange med hver sit slug, og en enkelt vare ligger i 16
 * kategorier. Det er ikke til at browse i, hvis man er 55 og bare har mus.
 *
 * Ingen af varerne har anmeldelser, og de fire, der er flaget som tilbud,
 * har samme før- og nu-pris. Derfor er der ikke et eneste ægte tilbud at
 * vise. Se DEALS i shopContent.
 */

/**
 * En størrelse af den samme vare. Hans "Mængde"-attribut, ordret, med prisen
 * og varenummeret der hører til lige den pakning.
 */
export type Variant = {
  /** Hans egen attributværdi, fx "25ltr" eller "5ltr koncentrat". */
  label: string;
  sku: string;
  price: number;
  inStock: boolean;
  /** Mængden læst ud af etiketten. 0 når den ikke kan læses. */
  amount: number;
  amountUnit: "" | "l" | "ml" | "g" | "kg" | "stk";
  /** Skal fortyndes før brug. Afgør, hvad beregneren regner på. */
  isConcentrate: boolean;
};

export type Product = {
  slug: string;
  name: string;
  sku: string;
  /** Kroner inkl. moms, som butikken viser dem. */
  price: number;
  /** Førpris. Kun et tilbud, når sale er sat og er lavere. */
  regular: number;
  sale: number | null;
  inStock: boolean;
  pest: PestKey;
  form: string;
  /** Filnavn under public/shop. */
  img: string;
  /** Hans egen korte beskrivelse, forkortet. */
  blurb: string;
  /** Mærket, læst ud af hans egne mærke-kategorier. Tomt når intet passer. */
  brand: string;
  /** Mængden, som han selv har skrevet den i varenavnet. */
  size: string;
  /** Enhedsprisen som tal, så listen kan sortere på den. 0 når der ingen er. */
  unitValue: number;
  /** Pris pr. 100 g, 100 ml eller stk. Tom når mængden ikke kan læses. */
  unit: string;
  /**
   * Størrelserne, når varen fås i flere. Tom for almindelige varer.
   * Baymard: varianter hører i én listevare, ikke i hver sin, ellers skal
   * kunden lede efter sin størrelse i en liste, der er blevet dobbelt så lang.
   */
  variants: Variant[];
  /** Dyreste variant. Lig price, når varen kun fås i én størrelse. */
  priceMax: number;
};

export type PestKey =
  | "alger"
  | "biller"
  | "edderkopper"
  | "fluer"
  | "fugle"
  | "hestebremse"
  | "hvepse"
  | "kakerlakker"
  | "lopper"
  | "moel"
  | "muldvarpe"
  | "mus"
  | "myrer"
  | "rotter"
  | "snegle"
  | "vaeggelus";

/** Kundens ord for skadedyret, og hvad han kalder det på servicesiden. */
export const PEST_LABEL: Record<PestKey, string> = {
  alger: "Alger",
  biller: "Biller",
  edderkopper: "Edderkopper",
  fluer: "Fluer",
  fugle: "Fugle",
  hestebremse: "Hestebremser",
  hvepse: "Hvepse",
  kakerlakker: "Kakerlakker",
  lopper: "Lopper",
  moel: "Møl",
  muldvarpe: "Muldvarpe",
  mus: "Mus",
  myrer: "Myrer",
  rotter: "Rotter",
  snegle: "Snegle",
  vaeggelus: "Væggelus",
};

export const PRODUCTS: Product[] = [
  {
    slug: "kvanol-10",
    name: "Kvanol 10 %",
    sku: "",
    price: 0,
    regular: 0,
    sale: null,
    inStock: true,
    pest: "alger",
    form: "Andet",
    img: "kvanol-10.jpg",
    blurb: "Kvanol 10% – Professionelt rengøringsmiddel mod grå belægninger, mug og dårlig lugt Effektiv fjernelse af alger, bakterier og svamp på tage, fliser, murværk og i drivhuse Kvanol 10% er et pr",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 0,
    variants: [],
  },
  {
    slug: "kvanol-50",
    name: "Kvanol 50%",
    sku: "",
    price: 0,
    regular: 0,
    sale: null,
    inStock: true,
    pest: "alger",
    form: "Andet",
    img: "kvanol-50.jpg",
    blurb: "Kvanol 50% – Professionelt rengøringsmiddel med Benzalkoniumklorid Effektiv fjernelse af bakterier, alger, svampe, mug og dårlig lugt Kvanol 50% er et professionelt rengøringsmiddel baseret ",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 0,
    variants: [],
  },
  {
    slug: "kvanol-algefjerner-proff",
    name: "Kvanol Algefjerner proff",
    sku: "37344",
    price: 99,
    regular: 99,
    sale: null,
    inStock: true,
    pest: "alger",
    form: "Andet",
    img: "kvanol-algefjerner-proff.jpg",
    blurb: "Kvanol Algefjerner Proff – Effektiv algebekæmpelse til tag, fliser og murværk Professionelt algemiddel til tegl- og betontag, træ, fliser og murværk Kvanol Algefjerner Proff er et effektivt ",
    brand: "",
    size: "5ltr",
    unit: "1,98 kr./100 ml",
    unitValue: 1.98,
    priceMax: 1399,
    variants: [
      { label: "5ltr", sku: "37344", price: 99, inStock: true, amount: 5, amountUnit: "l", isConcentrate: false },
      { label: "23ltr", sku: "37345", price: 1399, inStock: true, amount: 23, amountUnit: "l", isConcentrate: false },
    ],
  },
  {
    slug: "a-tox-25ltr",
    name: "A-Tox+",
    sku: "23018",
    price: 2099.95,
    regular: 2099.95,
    sale: null,
    inStock: true,
    pest: "biller",
    form: "Andet",
    img: "a-tox-25ltr.jpg",
    blurb: "A-Tox+ er et vandbaseret og transparent træbeskyttelsesmiddel til forebyggelse og bekæmpelse af træødelæggende insekter som borebiller og husbukke. Produktet anvendes på både nyt og gammelt ",
    brand: "Pelsis",
    size: "25ltr",
    unit: "8,40 kr./100 ml",
    unitValue: 8.3998,
    priceMax: 2599.95,
    variants: [
      { label: "25ltr", sku: "23018", price: 2099.95, inStock: true, amount: 25, amountUnit: "l", isConcentrate: false },
      { label: "5ltr koncentrat", sku: "1203001023", price: 2599.95, inStock: true, amount: 5, amountUnit: "l", isConcentrate: true },
    ],
  },
  {
    slug: "k-obiol-ec25",
    name: "K-Obiol EC25",
    sku: "110250",
    price: 2599.95,
    regular: 2599.95,
    sale: null,
    inStock: true,
    pest: "biller",
    form: "Gift",
    img: "k-obiol-ec25.jpg",
    blurb: "K-Obiol EC25 – professionelt insektmiddel til bekæmpelse af kornskadedyr Langtidsvirkende beskyttelse mod kornsnudebiller, melbiller og lagerinsekter K-Obiol EC25 er et professionelt insektm",
    brand: "ENVU",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 2599.95,
    variants: [],
  },
  {
    slug: "protox-kombi-protect",
    name: "Protox Kombi Protect",
    sku: "1047",
    price: 299.95,
    regular: 299.95,
    sale: null,
    inStock: true,
    pest: "biller",
    form: "Andet",
    img: "protox-kombi-protect.webp",
    blurb: "Protox Kombi Protect – Træbeskyttelse mod svampe, skimmelsvamp og træborende insekter Effektiv forebyggelse mod trænedbrydende svampe og borebiller Protox Kombi Protect er et brugsklart, van",
    brand: "",
    size: "1ltr",
    unit: "30,00 kr./100 ml",
    unitValue: 29.995,
    priceMax: 1049.95,
    variants: [
      { label: "1ltr", sku: "1047", price: 299.95, inStock: true, amount: 1, amountUnit: "l", isConcentrate: false },
      { label: "2,5ltr", sku: "1041", price: 599.95, inStock: true, amount: 25, amountUnit: "l", isConcentrate: false },
      { label: "5ltr", sku: "1042", price: 1049.95, inStock: true, amount: 5, amountUnit: "l", isConcentrate: false },
    ],
  },
  {
    slug: "protox-insekt",
    name: "Protox insekt",
    sku: "1038",
    price: 259.95,
    regular: 259.95,
    sale: null,
    inStock: true,
    pest: "biller",
    form: "Andet",
    img: "protox-insekt.webp",
    blurb: "Protox Insekt er et farveløst og vandbaseret træbeskyttelsesmiddel til forebyggelse og bekæmpelse af træborende insekter som borebiller og husbukke. Produktet kan anvendes på både nyt og gam",
    brand: "",
    size: "1ltr",
    unit: "26,00 kr./100 ml",
    unitValue: 25.995,
    priceMax: 2849,
    variants: [
      { label: "1ltr", sku: "1038", price: 259.95, inStock: false, amount: 1, amountUnit: "l", isConcentrate: false },
      { label: "2,5ltr", sku: "1031", price: 489.95, inStock: false, amount: 25, amountUnit: "l", isConcentrate: false },
      { label: "5ltr", sku: "1032", price: 1199.95, inStock: true, amount: 5, amountUnit: "l", isConcentrate: false },
      { label: "5ltr koncentrat (30ltr)", sku: "150238", price: 2849, inStock: true, amount: 5, amountUnit: "l", isConcentrate: true },
    ],
  },
  {
    slug: "pest-stop-universel-insektspray-mod-insekter-billigskadedyr-dk",
    name: "Pest-Stop Universel insektspray",
    sku: "",
    price: 159.95,
    regular: 159.95,
    sale: null,
    inStock: true,
    pest: "edderkopper",
    form: "Spray",
    img: "pest-stop-universel-insektspray-mod-insekter-bil.jpg",
    blurb: "Pest-Stop Universel Insektspray – effektiv bekæmpelse af krybende og flyvende insekter Hurtig løsning mod insekter i hjemmet Oplever du myrer, sølvfisk, edderkopper eller andre generende ins",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 159.95,
    variants: [],
  },
  {
    slug: "provecta",
    name: "Provecta",
    sku: "126914",
    price: 1449,
    regular: 1449,
    sale: null,
    inStock: true,
    pest: "edderkopper",
    form: "Spray",
    img: "provecta.webp",
    blurb: "Provecta – fysisk insektmiddel mod flyvende og kravlende insekter Provecta er et innovativt insektmiddel, der virker ved en fysisk fastholdelse frem for traditionelle kemiske insekticider. P",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 1449,
    variants: [],
  },
  {
    slug: "trinol-810-insektmiddel",
    name: "Trinol 810 insektmiddel",
    sku: "100500",
    price: 199,
    regular: 199,
    sale: null,
    inStock: true,
    pest: "edderkopper",
    form: "Spray",
    img: "trinol-810-insektmiddel.webp",
    blurb: "Trinol 810 Insektspray er et effektivt og brugervenligt insektmiddel til bekæmpelse af havemyrer udendørs. Produktet er vandbaseret og udviklet til målrettet behandling af områder, hvor myre",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 199,
    variants: [],
  },
  {
    slug: "trinol-insect-freeze",
    name: "Trinol Insect Freeze",
    sku: "100507",
    price: 149,
    regular: 149,
    sale: null,
    inStock: true,
    pest: "edderkopper",
    form: "Spray",
    img: "trinol-insect-freeze.webp",
    blurb: "Trinol Insect Freeze er en effektiv og øjeblikkelig løsning til bekæmpelse af insekter ved hjælp af ekstrem kulde. Sprayen nedkøler insekter til helt ned til -45 °C, hvilket enten dræber dem",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 149,
    variants: [],
  },
  {
    slug: "absorbine-ultrashield-fluespray",
    name: "Absorbine UltraShield Fluespray",
    sku: "105370",
    price: 499,
    regular: 499,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Spray",
    img: "absorbine-ultrashield-fluespray.webp",
    blurb: "Absorbine UltraShield Fluespray er en professionel og langtidsvirkende insektspray til heste og ponyer, udviklet til effektiv beskyttelse mod fluer, myg, klæg og andre bidende insekter. Prod",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 499,
    variants: [],
  },
  {
    slug: "bananfluefaelde",
    name: "Bananfluefælde",
    sku: "3606",
    price: 69.95,
    regular: 69.95,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Fælde",
    img: "bananfluefaelde.jpg",
    blurb: "Effektiv løsning mod bananfluer og frugtfluer i hjemmet Er du træt af små frugtfluer omkring frugtskålen? GP Bananfluefælde er en diskret og effektiv løsning til bekæmpelse af bananfluer og ",
    brand: "Pelsis",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 69.95,
    variants: [],
  },
  {
    slug: "flue-chok",
    name: "Flue Chok 750ml",
    sku: "102165",
    price: 199.95,
    regular: 199.95,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Andet",
    img: "flue-chok.jpg",
    blurb: "Flue Chok – effektiv bekæmpelse af fluer indendørs og i erhverv Flue Chok er en effektiv løsning til hurtig bekæmpelse af fluer, når problemet skal stoppes med det samme. Produktet er udvikl",
    brand: "Pelsis",
    size: "750 ml",
    unit: "26,66 kr./100 ml",
    unitValue: 0,
    priceMax: 199.95,
    variants: [],
  },
  {
    slug: "fly-trap-fluefaelde",
    name: "Fly Trap Fluefælde",
    sku: "3441",
    price: 74.95,
    regular: 74.95,
    sale: null,
    inStock: false,
    pest: "fluer",
    form: "Fælde",
    img: "fly-trap-fluefaelde.jpg",
    blurb: "Fly Trap fluefælde er en meget effektiv løsning til at bekæmpe fluer i stald, have eller andre udearealer. Fly Trap bruger ikke gift og kan fange op imod 20.000 fluer i en fælde uden at skul",
    brand: "Pelsis",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 74.95,
    variants: [],
  },
  {
    slug: "fly-in-monster-fluefaelde",
    name: "Fly-in Monster fluefælde",
    sku: "120203",
    price: 49.95,
    regular: 49.95,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Fælde",
    img: "fly-in-monster-fluefaelde.jpg",
    blurb: "Fly-In Monster fluefælde er en kraftig og effektiv løsning til bekæmpelse af fluer udendørs. Fælden er udviklet til brug på terrasser, ved indgange og i områder med husdyr som grise, køer, h",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 1599.95,
    variants: [
      { label: "Fly-in Monster Refill", sku: "120203", price: 49.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Fly-in Monster Mini", sku: "120200", price: 649.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Fly-in Monster Stor", sku: "120201", price: 1599.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "frugtfluefaelde",
    name: "Frugtfluefælde",
    sku: "3428",
    price: 49.95,
    regular: 49.95,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Fælde",
    img: "frugtfluefaelde.jpg",
    blurb: "Frugtfluefælden er en diskret og effektiv løsning mod frugtfluer , også kendt som bananfluer eller eddikefluer. Fælden bruger et attraktivt lokkemiddel, som tiltrækker de små fluer, hvorefte",
    brand: "Pelsis",
    size: "15ml",
    unit: "333,00 kr./100 ml",
    unitValue: 333,
    priceMax: 169.95,
    variants: [
      { label: "15ml", sku: "3428", price: 49.95, inStock: true, amount: 15, amountUnit: "ml", isConcentrate: false },
      { label: "200ml refill", sku: "3492", price: 89.95, inStock: true, amount: 200, amountUnit: "ml", isConcentrate: false },
      { label: "200ml", sku: "3490", price: 169.95, inStock: true, amount: 200, amountUnit: "ml", isConcentrate: false },
    ],
  },
  {
    slug: "frugtfluefaelde-prof",
    name: "Frugtfluefælde Prof",
    sku: "125580",
    price: 59,
    regular: 59,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Fælde",
    img: "frugtfluefaelde-prof.webp",
    blurb: "Frugtfluefælde Prof – effektiv fælde med stor kapacitet Frugtfluer kan hurtigt blive et irriterende problem i køkkener, restauranter og andre steder, hvor fødevarer håndteres eller opbevares",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 119,
    variants: [
      { label: "Fælde", sku: "125580", price: 59, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "200ml Lokkemiddel", sku: "125581", price: 89, inStock: true, amount: 200, amountUnit: "ml", isConcentrate: false },
      { label: "400ml lokkemiddel", sku: "130666", price: 119, inStock: true, amount: 400, amountUnit: "ml", isConcentrate: false },
    ],
  },
  {
    slug: "klisterfaelde-10stk",
    name: "Klisterfælde 10stk",
    sku: "",
    price: 249,
    regular: 249,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Fælde",
    img: "klisterfaelde-10stk.jpg",
    blurb: "Black Stripe Delta klisterfælder er en effektiv løsning til monitorering og bekæmpelse af krybende og flyvende insekter – særligt møl og skægkræ. Fælderne anvendes sammen med lokkestof (fero",
    brand: "",
    size: "10 stk",
    unit: "24,90 kr./stk.",
    unitValue: 0,
    priceMax: 249,
    variants: [],
  },
  {
    slug: "ps-flue-stop",
    name: "PS Flue Stop",
    sku: "",
    price: 129.95,
    regular: 129.95,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Andet",
    img: "ps-flue-stop.jpg",
    blurb: "PS Flue Stop er en alsidig og effektiv insekt spray, der bekæmper både flyvende og kravlende insekter i og omkring bygninger. Produktet er udviklet til helrumsbehandling mod fluer, myg og hv",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 129.95,
    variants: [],
  },
  {
    slug: "trinol-fluepose",
    name: "Trinol Fluepose",
    sku: "100707",
    price: 69,
    regular: 69,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Andet",
    img: "trinol-fluepose.jpg",
    blurb: "Trinol Fluepose, også kendt som Flybag, er en effektiv engangsfælde til bekæmpelse af fluer i udendørs miljøer. Fælden er udviklet til at håndtere både stuefluer og stikfluer og er særligt v",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 69,
    variants: [],
  },
  {
    slug: "trinol-fluespiral",
    name: "Trinol Fluespiral 4stk",
    sku: "",
    price: 19,
    regular: 19,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Andet",
    img: "trinol-fluespiral.jpg",
    blurb: "Trinol Fluespiral er en klassisk og effektiv løsning til bekæmpelse af flyvende insekter – helt uden brug af giftstoffer eller dampe. Spiralerne fungerer som klisterfælder, der tiltrækker og",
    brand: "Trinol",
    size: "4 stk",
    unit: "4,75 kr./stk.",
    unitValue: 0,
    priceMax: 19,
    variants: [],
  },
  {
    slug: "trinol-frugtfluefaelde",
    name: "Trinol Frugtfluefælde",
    sku: "100704",
    price: 69.95,
    regular: 69.95,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Fælde",
    img: "trinol-frugtfluefaelde.jpg",
    blurb: "Trinol Frugtfluefælde er fælde der bruges til bekæmpelse og fangst af bananfluer også kaldet frugtfluer i hjemmet. Fælden er meget let at anvende. Fluerne tiltrækkes væsken i beholderen og s",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 69.95,
    variants: [],
  },
  {
    slug: "trinol-sticky-bug",
    name: "Trinol Sticky Bug",
    sku: "100706",
    price: 59,
    regular: 59,
    sale: null,
    inStock: true,
    pest: "fluer",
    form: "Andet",
    img: "trinol-sticky-bug.jpg",
    blurb: "Trinol Sticky Bug er en effektiv diskret fælde til din potte plante eller altankasse. Sticky Bug er en insektticid- og lugtfri klæbefælde resistent i alt slags vejr. Fælden kan klare alle te",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 59,
    variants: [],
  },
  {
    slug: "avifix-290ml-monteringslim",
    name: "Avifix 290ml monteringslim",
    sku: "7216",
    price: 109,
    regular: 109,
    sale: null,
    inStock: true,
    pest: "fugle",
    form: "Sikring",
    img: "avifix-290ml-monteringslim.jpg",
    blurb: "Avifix 290 ml monteringslim er et stærkt og alsidigt klæbemiddel, der er udviklet til montering af fuglesikring – særligt silikonebaserede løsninger som fuglepigge og andre afskrækkere. Lime",
    brand: "",
    size: "290 ml",
    unit: "37,59 kr./100 ml",
    unitValue: 0,
    priceMax: 109,
    variants: [],
  },
  {
    slug: "avipoint-g20-fuglepigge",
    name: "Avipoint G20 fuglepigge",
    sku: "27007",
    price: 79,
    regular: 79,
    sale: null,
    inStock: true,
    pest: "fugle",
    form: "Sikring",
    img: "avipoint-g20-fuglepigge.jpg",
    blurb: "Avipoint G20 fuglepigge er en professionel løsning til effektiv fuglesikring af bygninger, altaner, tagrender og andre overflader. Produktet er udviklet til at forhindre fugle i at lande og ",
    brand: "",
    size: "Clips til bjælker 10stk",
    unit: "7,90 kr./stk.",
    unitValue: 7.9,
    priceMax: 4499,
    variants: [
      { label: "Clips til bjælker 10stk", sku: "27007", price: 79, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Clips til tagrende 10stk", sku: "27134", price: 79, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Clips til vinduer 10stk", sku: "27133", price: 99, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Avipoint G20 fuglepigge 5m", sku: "27033", price: 499, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Clips til solpaneler & tagrykke", sku: "7215", price: 699, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Clips til tagrende med vulst 10stk", sku: "7218", price: 699, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Avipoint G20 fuglepigge 50m", sku: "27135", price: 4499, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "avipoint-p14-fuglepigge",
    name: "Avipoint P14 fuglepigge",
    sku: "27007-1-1",
    price: 79,
    regular: 79,
    sale: null,
    inStock: true,
    pest: "fugle",
    form: "Sikring",
    img: "avipoint-p14-fuglepigge.jpg",
    blurb: "Avipoint P14 fuglepigge er en professionel og diskret løsning til effektiv fuglesikring på smalle overflader. Produktet er særligt udviklet til at forhindre duer i at lande på rør, smalle af",
    brand: "",
    size: "Clips til bjælker 10stk",
    unit: "7,90 kr./stk.",
    unitValue: 7.9,
    priceMax: 4299,
    variants: [
      { label: "Clips til bjælker 10stk", sku: "27007-1-1", price: 79, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Clips til tagrende 10stk", sku: "27134-1-1", price: 79, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Clips til solpaneler & tagrykke", sku: "7215-1-1", price: 699, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Clips til tagrende med vulst 10stk", sku: "7218-1-1", price: 699, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Avipoint P14 fuglepigge 5m", sku: "7212", price: 899, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Avipoint P14 fuglepigge 50m", sku: "7211", price: 4299, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "avipoint-p20-fuglepigge",
    name: "Avipoint P20 fuglepigge",
    sku: "27007-1",
    price: 79,
    regular: 79,
    sale: null,
    inStock: true,
    pest: "fugle",
    form: "Sikring",
    img: "avipoint-p20-fuglepigge.jpg",
    blurb: "Avipoint P20 fuglepigge er en professionel og diskret løsning til effektiv fuglesikring – særligt udviklet til bekæmpelse af duer. Produktet forhindrer fugle i at lande og opholde sig på byg",
    brand: "",
    size: "Clips til bjælker 10stk",
    unit: "7,90 kr./stk.",
    unitValue: 7.9,
    priceMax: 4499,
    variants: [
      { label: "Clips til bjælker 10stk", sku: "27007-1", price: 79, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Clips til tagrende 10stk", sku: "27134-1", price: 79, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Avipoint P20 fuglepigge 5m", sku: "27091", price: 449, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Clips til solpaneler & tagrykke", sku: "7215-1", price: 699, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Clips til tagrende med vulst 10stk", sku: "7218-1", price: 699, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Avipoint P20 fuglepigge 50m", sku: "27123", price: 4499, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "avipoint-p32-fuglepigge",
    name: "Avipoint P32 fuglepigge",
    sku: "27007-1-1-1",
    price: 79,
    regular: 79,
    sale: null,
    inStock: true,
    pest: "fugle",
    form: "Sikring",
    img: "avipoint-p32-fuglepigge.jpg",
    blurb: "Avipoint P32 fuglepigge er en professionel løsning til effektiv fuglesikring i områder med høj fugleaktivitet. Produktet er særligt udviklet til at håndtere både duer og stære, hvor der er b",
    brand: "",
    size: "Clips til bjælker 10stk",
    unit: "7,90 kr./stk.",
    unitValue: 7.9,
    priceMax: 8999,
    variants: [
      { label: "Clips til bjælker 10stk", sku: "27007-1-1-1", price: 79, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Clips til tagrende 10stk", sku: "27134-1-1-1", price: 79, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Clips til solpaneler & tagrykke", sku: "7215-1-1-1", price: 699, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Clips til tagrende med vulst 10stk", sku: "7218-1-1-1", price: 699, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Avipoint P32 fuglepigge 5m", sku: "7214", price: 1399, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Avipoint P32 fuglepigge 50m", sku: "7213", price: 8999, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "avisil-310g-monteringslim",
    name: "Avisil 310g monteringslim",
    sku: "7139",
    price: 199.95,
    regular: 199.95,
    sale: null,
    inStock: true,
    pest: "fugle",
    form: "Sikring",
    img: "avisil-310g-monteringslim.jpg",
    blurb: "Avisil 310 g monteringslim er et klart, højkvalitets silikonebaseret klæbemiddel, udviklet til professionel montering af fuglesikring. Limen er neutralhærdende, UV-resistent og kan anvendes ",
    brand: "",
    size: "310 g",
    unit: "64,50 kr./100 g",
    unitValue: 0,
    priceMax: 199.95,
    variants: [],
  },
  {
    slug: "hestebremsefaelde",
    name: "Hestebremsefælde",
    sku: "103159",
    price: 1499,
    regular: 1499,
    sale: null,
    inStock: true,
    pest: "hestebremse",
    form: "Fælde",
    img: "hestebremsefaelde.webp",
    blurb: "Hestebremsefælde er en effektiv og giftfri løsning til bekæmpelse af klæger og hestebremser på marker, folde og andre udendørs arealer med heste og husdyr. Fælden udnytter insekternes naturl",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 1499,
    variants: [],
  },
  {
    slug: "aquapy-1ltr",
    name: "AquaPy 1ltr",
    sku: "110341",
    price: 2999.95,
    regular: 2999.95,
    sale: null,
    inStock: true,
    pest: "hvepse",
    form: "Spray",
    img: "aquapy-1ltr.jpg",
    blurb: "AquaPy 1 ltr – professionelt insektmiddel mod alle insekter Hurtig knock-down effekt mod flyvende og krybende insekter Har du problemer med fluer, myg, væggelus, kakerlakker eller andre inse",
    brand: "ENVU",
    size: "1 l",
    unit: "300,00 kr./100 ml",
    unitValue: 0,
    priceMax: 2999.95,
    variants: [],
  },
  {
    slug: "green-hero-frost",
    name: "Green Hero Frost",
    sku: "160128",
    price: 249,
    regular: 249,
    sale: null,
    inStock: true,
    pest: "hvepse",
    form: "Spray",
    img: "green-hero-frost.jpg",
    blurb: "Green Hero Frost – Giftfri frysespray til øjeblikkelig bekæmpelse af insekter Effektiv og human bekæmpelse med ekstrem kulde Green Hero Frost er en kraftig frysespray, der hurtigt og effekti",
    brand: "Vilofarm",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 249,
    variants: [],
  },
  {
    slug: "green-protect-hvepsefaelde",
    name: "Green Protect Hvepsefælde & Lokkemiddel",
    sku: "23616",
    price: 129.95,
    regular: 129.95,
    sale: null,
    inStock: true,
    pest: "hvepse",
    form: "Fælde",
    img: "green-protect-hvepsefaelde.jpg",
    blurb: "Green Protect Hvepsefælde & Lokkemiddel er en effektiv og giftfri løsning til at reducere hvepse og flyvende insekter i haven. Fælden anvender en ugiftig opløsning, som tiltrækker hvepse og ",
    brand: "GreenProtect",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 129.95,
    variants: [],
  },
  {
    slug: "hvepsefaelde-lokkemiddel",
    name: "Hvepsefælde / Lokkemiddel",
    sku: "23617",
    price: 69,
    regular: 69,
    sale: null,
    inStock: true,
    pest: "hvepse",
    form: "Fælde",
    img: "hvepsefaelde-lokkemiddel.jpg",
    blurb: "Hvepsefælde – effektiv løsning mod hvepse i haven og ved terrassen Reducér hvepse omkring hjemmet uden brug af spray Er du generet af hvepse omkring terrassen, grillen eller udendørs spiseom",
    brand: "",
    size: "Lokkemiddel 500ml",
    unit: "13,80 kr./100 ml",
    unitValue: 13.8,
    priceMax: 79,
    variants: [
      { label: "Lokkemiddel 500ml", sku: "23617", price: 69, inStock: true, amount: 500, amountUnit: "ml", isConcentrate: false },
      { label: "Hvepsefælde", sku: "23012", price: 79, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "hvepselokkemiddel",
    name: "Hvepselokkemiddel 1ltr / 5ltr",
    sku: "23020",
    price: 199.95,
    regular: 199.95,
    sale: 199.95,
    inStock: true,
    pest: "hvepse",
    form: "Lokkemiddel",
    img: "hvepselokkemiddel.jpg",
    blurb: "Hvepselokkemiddel 1ltr / 5ltr – effektiv tiltrækning til hvepsefælder Målrettet løsning mod hvepse i haven, ved terrassen og omkring bygninger Oplever du mange hvepse omkring hjemmet, på ter",
    brand: "Pelsis",
    size: "1ltr",
    unit: "19,99 kr./100 ml",
    unitValue: 19.995,
    priceMax: 499.95,
    variants: [
      { label: "1ltr", sku: "23020", price: 199.95, inStock: false, amount: 1, amountUnit: "l", isConcentrate: false },
      { label: "5ltr", sku: "23021", price: 499.95, inStock: true, amount: 5, amountUnit: "l", isConcentrate: false },
    ],
  },
  {
    slug: "k-othrine-partix",
    name: "K-Othrine Partix 240ml",
    sku: "110262",
    price: 1699.95,
    regular: 1699.95,
    sale: null,
    inStock: true,
    pest: "hvepse",
    form: "Spray",
    img: "k-othrine-partix.jpg",
    blurb: "K-Othrine Partix 240 ml – Professionelt insektmiddel med langtidseffekt op til 12 uger Effektiv bekæmpelse af væggelus, kakerlakker, edderkopper og krybende insekter – med avanceret Partix-t",
    brand: "ENVU",
    size: "240 ml",
    unit: "708,31 kr./100 ml",
    unitValue: 0,
    priceMax: 1699.95,
    variants: [],
  },
  {
    slug: "pest-stop-hvepsespray",
    name: "PS Hvepsespray PROFF",
    sku: "2466",
    price: 139.95,
    regular: 139.95,
    sale: null,
    inStock: true,
    pest: "hvepse",
    form: "Spray",
    img: "pest-stop-hvepsespray.jpg",
    blurb: "PS Hvepsespray – effektiv bekæmpelse af hvepse og hvepsebo Hurtig og målrettet løsning mod hvepse omkring hjemmet Har du hvepse ved terrassen, under tagudhæng eller omkring huset? PS Hvepses",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 139.95,
    variants: [],
  },
  {
    slug: "perma-forte-b",
    name: "Perma Forte B",
    sku: "",
    price: 0,
    regular: 0,
    sale: null,
    inStock: true,
    pest: "hvepse",
    form: "Spray",
    img: "perma-forte-b.jpg",
    blurb: "Perma Forte B, er et ekstremt effektivt produkt, som virker øjeblikkeligt dræbende på alle insekter, som f.eks. myrere, hvepse, fluer, kakerlakker, biller, sølvfisk, skægkræ, lus og lopper. ",
    brand: "Vilofarm",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 0,
    variants: [],
  },
  {
    slug: "trinol-turbo-jet",
    name: "Trinol Turbo Jet",
    sku: "110360",
    price: 189.95,
    regular: 189.95,
    sale: null,
    inStock: true,
    pest: "hvepse",
    form: "Spray",
    img: "trinol-turbo-jet.webp",
    blurb: "Trinol Turbo Jet – kraftig spray mod fluer, hvepse og flyvende insekter Effektiv knock-down bekæmpelse af fluer og hvepse Har du problemer med fluer i hjemmet, garagen eller stalden? Trinol ",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 189.95,
    variants: [],
  },
  {
    slug: "advion-gel",
    name: "Advion Gel",
    sku: "110269-1",
    price: 629,
    regular: 629,
    sale: null,
    inStock: true,
    pest: "kakerlakker",
    form: "Gel",
    img: "advion-gel.jpg",
    blurb: "Advion Gel er en effektiv og professionel insektgel til bekæmpelse af skægkræ, sølvfisk og kakerlakker . Gelen har en høj ædelyst og placeres målrettet dér, hvor insekterne færdes, så selv s",
    brand: "",
    size: "1x30g",
    unit: "2096,67 kr./100 g",
    unitValue: 2096.67,
    priceMax: 2399,
    variants: [
      { label: "1x30g", sku: "110269-1", price: 629, inStock: true, amount: 30, amountUnit: "g", isConcentrate: false },
      { label: "2x30g", sku: "", price: 1199, inStock: true, amount: 60, amountUnit: "g", isConcentrate: false },
      { label: "4x30g", sku: "110269", price: 2399, inStock: true, amount: 120, amountUnit: "g", isConcentrate: false },
    ],
  },
  {
    slug: "deltasect",
    name: "Deltasect 1ltr",
    sku: "481034",
    price: 1899,
    regular: 1899,
    sale: null,
    inStock: true,
    pest: "kakerlakker",
    form: "Spray",
    img: "deltasect.jpg",
    blurb: "Deltasect – Effektivt insektmiddel mod myrer og kakerlakker til indendørs brug Målrettet bekæmpelse af krybende insekter i bygninger Deltasect er et flydende insektmiddel udviklet til effekt",
    brand: "",
    size: "1 l",
    unit: "189,90 kr./100 ml",
    unitValue: 0,
    priceMax: 1899,
    variants: [],
  },
  {
    slug: "maxforce-platin",
    name: "Maxforce Platin",
    sku: "110273",
    price: 4599,
    regular: 4599,
    sale: null,
    inStock: true,
    pest: "kakerlakker",
    form: "Andet",
    img: "maxforce-platin.jpg",
    blurb: "Maxforce Platin – Professionel gel mod skægget sølvkræ og kakerlakker indendørs Langtidsholdbar insektgel med høj tiltrækningskraft til målrettet bekæmpelse af krybende insekter Maxforce Pla",
    brand: "ENVU",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 4599,
    variants: [],
  },
  {
    slug: "trinol-deet-spray-40",
    name: "Trinol DEET Spray 40%",
    sku: "",
    price: 99,
    regular: 99,
    sale: null,
    inStock: true,
    pest: "lopper",
    form: "Spray",
    img: "trinol-deet-spray-40.jpg",
    blurb: "Trinol DEET Spray 40% er en højtydende mygge- og flåtspray, der giver effektiv beskyttelse mod insektbid og stik. Produktet indeholder aktivstoffet DEET og er særligt velegnet til rejser, ud",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 99,
    variants: [],
  },
  {
    slug: "trinol-klaedemoel-detektor",
    name: "Trinol Klædemøl Detektor",
    sku: "130247",
    price: 79,
    regular: 79,
    sale: null,
    inStock: true,
    pest: "moel",
    form: "Overvågning",
    img: "trinol-klaedemoel-detektor.webp",
    blurb: "Trinol Klædemøl Detektor – effektiv overvågning af møl i tøj og tekstiler Klædemøl kan forårsage store skader på tøj, tæpper og andre tekstiler i hjemmet. Ofte opdages problemet først, når d",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 79,
    variants: [],
  },
  {
    slug: "trinol-melmoel-detektor",
    name: "Trinol Melmøl Detektor",
    sku: "130248",
    price: 79,
    regular: 79,
    sale: null,
    inStock: true,
    pest: "moel",
    form: "Overvågning",
    img: "trinol-melmoel-detektor.webp",
    blurb: "Trinol Melmøl Detektor – overvågning af melmøl i køkkenskabe og tørvarer Melmøl er et almindeligt problem i mange køkkener, hvor de kan angribe tørvarer som mel, ris, havregryn, nødder og an",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 79,
    variants: [],
  },
  {
    slug: "fosforbrinte",
    name: "Fosforbrinte",
    sku: "150015",
    price: 2299,
    regular: 2299,
    sale: null,
    inStock: true,
    pest: "muldvarpe",
    form: "Sikring",
    img: "fosforbrinte.jpg",
    blurb: "Trinol Fosforbrinte er et professionelt og yderst effektivt middel til bekæmpelse af muldvarpe og mosegrise. Produktet består af pellets, som ved kontakt med fugt og ilt i jorden udvikler fo",
    brand: "",
    size: "Fosforbrinte 1kg",
    unit: "229,90 kr./100 g",
    unitValue: 229.9,
    priceMax: 3899.95,
    variants: [
      { label: "Fosforbrinte 1kg", sku: "150015", price: 2299, inStock: true, amount: 1, amountUnit: "kg", isConcentrate: false },
      { label: "Opstartssæt inkl Fosforbrinte", sku: "150014", price: 3899.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "muldvarpesaks-med-lang-haandtag",
    name: "Muldvarpesaks med lang håndtag",
    sku: "1340",
    price: 49,
    regular: 49,
    sale: null,
    inStock: true,
    pest: "muldvarpe",
    form: "Sikring",
    img: "muldvarpesaks-med-lang-haandtag.jpg",
    blurb: "Muldvarpesaks med langt håndtag er en effektiv og klassisk løsning til bekæmpelse af muldvarpe i haven. Fælden er fremstillet i galvaniseret stål, hvilket gør den særligt robust og velegnet ",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 49,
    variants: [],
  },
  {
    slug: "pest-stop-muldvarpesaks",
    name: "Pest-Stop muldvarpesaks",
    sku: "2456",
    price: 89.95,
    regular: 89.95,
    sale: null,
    inStock: true,
    pest: "muldvarpe",
    form: "Sikring",
    img: "pest-stop-muldvarpesaks.jpg",
    blurb: "Pest-Stop Muldvarpesaks – effektiv fælde til bekæmpelse af muldvarpe i haven Slip af med muldvarpeskud og ødelagte græsplæner Oplever du muldvarpeskud, der ødelægger plænen eller blomsterbed",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 89.95,
    variants: [],
  },
  {
    slug: "spinner-muldvarpefaelde",
    name: "Spinner muldvarpefælde",
    sku: "120150",
    price: 69.95,
    regular: 69.95,
    sale: null,
    inStock: true,
    pest: "muldvarpe",
    form: "Fælde",
    img: "spinner-muldvarpefaelde.jpg",
    blurb: "Spinner muldvarpefælde er en klassisk og effektiv mekanisk fælde til bekæmpelse af muldvarpe i græsplæner, haver og andre udendørsarealer. Fælden placeres direkte i muldvarpens aktive gang, ",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 69.95,
    variants: [],
  },
  {
    slug: "trinol-mole-trap",
    name: "Trinol mole trap",
    sku: "100585",
    price: 69.95,
    regular: 69.95,
    sale: null,
    inStock: true,
    pest: "muldvarpe",
    form: "Fælde",
    img: "trinol-mole-trap.jpg",
    blurb: "Trinol mole trap er en effektiv giftfri måde at bekæmpe muldvarpe i din græsplæne. Produktet bruges målrettet efter den konkrete opgave og den medfølgende anvisning, så placering, kontrol og",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 69.95,
    variants: [],
  },
  {
    slug: "24-7-iq-musefaelde",
    name: "24/7 IQ Musefælde",
    sku: "140421",
    price: 499,
    regular: 499,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "24-7-iq-musefaelde.jpg",
    blurb: "24/7 IQ musefælde er en avanceret løsning til human musebekæmpelse kombineret med moderne Bell IQ sensor teknologi. Fælden fanger mus levende og registrerer samtidig aktivitet, som sendes di",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 499,
    variants: [],
  },
  {
    slug: "alfa-korn-mod-mus",
    name: "Alfa korn musegift",
    sku: "",
    price: 0,
    regular: 0,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "alfa-korn-mod-mus.webp",
    blurb: "Alfa Korn musegift er et effektivt rodenticid udviklet til målrettet bekæmpelse af mus i og omkring bygninger. Produktet består af kornbaseret gift, som udnytter musenes naturlige fødepræfer",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 0,
    variants: [],
  },
  {
    slug: "alfa-musegiftstation",
    name: "Alfa musegiftstation 2stk",
    sku: "100600",
    price: 29.95,
    regular: 29.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "alfa-musegiftstation.jpg",
    blurb: "Alfa Musegiftstation 2 stk – Sikker og diskret løsning til bekæmpelse af mus Effektiv musebekæmpelse med fokus på sikkerhed og kontrol Har du problemer med mus i hjemmet, garagen eller omkri",
    brand: "Trinol",
    size: "2 stk",
    unit: "14,97 kr./stk.",
    unitValue: 0,
    priceMax: 29.95,
    variants: [],
  },
  {
    slug: "black-pearl-korn",
    name: "Black Pearl korn",
    sku: "102433",
    price: 999.95,
    regular: 999.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "black-pearl-korn.webp",
    blurb: "Black Pearl korn er et super effektivt middel til skånsom og giftfri bekæmpelse af mus indendørs. Fremstillet på en blanding af overskårne havrekerner og aktivstoffet alphachloralose. Black ",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 999.95,
    variants: [],
  },
  {
    slug: "edialux-warden",
    name: "Edialux Warden",
    sku: "1101077941",
    price: 39.95,
    regular: 39.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "edialux-warden.jpg",
    blurb: "Edialux Warden er en kompakt og robust lokkemadsstation, udviklet til sikker og effektiv håndtering af museproblemer. Stationen er fremstillet i UV-stabiliseret polypropylen og designet til ",
    brand: "Edialux",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 39.95,
    variants: [],
  },
  {
    slug: "goodnature-a24",
    name: "GoodNature A24",
    sku: "170882",
    price: 49,
    regular: 49,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "goodnature-a24.jpg",
    blurb: "Goodnature A24 – fuldautomatisk og giftfri fælde til rotter og mus Moderne og vedvarende bekæmpelse uden brug af gift Har du problemer med rotter eller mus og ønsker en effektiv løsning uden",
    brand: "Good Nature",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 1599,
    variants: [
      { label: "CO2 patron", sku: "170882", price: 49, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Automatisk lokkemadspumpe", sku: "758702", price: 129.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "A24-blokering", sku: "483018", price: 299.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "1års refill pakke", sku: "750850", price: 329, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Sikkerhedsboks", sku: "170887", price: 699.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "GoodNature A24 Startsæt", sku: "758641", price: 1099, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Good-Nature A24 Smart Trap Kit", sku: "170889", price: 1599, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "metal-smaekfaelde-proff",
    name: "Metal smækfælde Proff",
    sku: "2163",
    price: 19.95,
    regular: 19.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "metal-smaekfaelde-proff.jpg",
    blurb: "Metal Smækfælde Proff – kraftig smækfælde til mus og rotter Effektiv og klassisk løsning mod mus og rotter Har du problemer med mus eller rotter i hjemmet, garagen eller virksomheden? Metal ",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 29.95,
    variants: [
      { label: "Musesmækfælde Proff", sku: "2163", price: 19.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Rottesmækfælde Proff", sku: "2158", price: 29.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "nara-lure-lokkeblok",
    name: "Nara Lure lokkeblok",
    sku: "",
    price: 99,
    regular: 99,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "nara-lure-lokkeblok.jpg",
    blurb: "Nara Lure Lokkeblok – professionelt lokkemiddel til rotter og mus Kraftig aroma der tiltrækker gnavere i op til 3 måneder Nara Lure Lokkeblok er et professionelt lokkemiddel udviklet til eff",
    brand: "",
    size: "Vanille 10stk",
    unit: "9,90 kr./stk.",
    unitValue: 9.9,
    priceMax: 599,
    variants: [
      { label: "Vanille 10stk", sku: "", price: 99, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Choco-Nut 10stk", sku: "", price: 99, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Fisk 10stk", sku: "", price: 99, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Kød 10stk", sku: "", price: 99, inStock: true, amount: 10, amountUnit: "stk", isConcentrate: false },
      { label: "Vanille 20stk", sku: "", price: 199, inStock: true, amount: 20, amountUnit: "stk", isConcentrate: false },
      { label: "Choco-Nut 20stk", sku: "", price: 199, inStock: true, amount: 20, amountUnit: "stk", isConcentrate: false },
      { label: "Fisk 20stk", sku: "", price: 199, inStock: true, amount: 20, amountUnit: "stk", isConcentrate: false },
      { label: "Kød 20stk", sku: "", price: 199, inStock: true, amount: 20, amountUnit: "stk", isConcentrate: false },
      { label: "Vanille 50stk", sku: "", price: 349, inStock: true, amount: 50, amountUnit: "stk", isConcentrate: false },
      { label: "Choco-Nut 50stk", sku: "", price: 349, inStock: true, amount: 50, amountUnit: "stk", isConcentrate: false },
      { label: "Fisk 50stk", sku: "", price: 349, inStock: true, amount: 50, amountUnit: "stk", isConcentrate: false },
      { label: "Kød 50stk", sku: "", price: 349, inStock: true, amount: 50, amountUnit: "stk", isConcentrate: false },
      { label: "Vanille 100stk", sku: "", price: 599, inStock: true, amount: 100, amountUnit: "stk", isConcentrate: false },
      { label: "Choco-Nut 100stk", sku: "", price: 599, inStock: true, amount: 100, amountUnit: "stk", isConcentrate: false },
      { label: "Fisk 100stk", sku: "", price: 599, inStock: true, amount: 100, amountUnit: "stk", isConcentrate: false },
      { label: "Kød 100stk", sku: "", price: 599, inStock: true, amount: 100, amountUnit: "stk", isConcentrate: false },
    ],
  },
  {
    slug: "ps-trip-trap-musefaelde",
    name: "PS Trip-Trap Musefælde",
    sku: "2415",
    price: 39,
    regular: 39,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "ps-trip-trap-musefaelde.jpg",
    blurb: "PS Trip-Trap musefælde er en sikker og human løsning til håndtering af uønskede mus – helt uden brug af gift eller dræbende mekanismer. Fælden fanger musen levende, så den kan sættes fri ige",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 39,
    variants: [],
  },
  {
    slug: "pest-stop-automatisk-musefaelde",
    name: "Pest-Stop Automatisk musefælde",
    sku: "2435",
    price: 179,
    regular: 179,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "pest-stop-automatisk-musefaelde.jpg",
    blurb: "Pest-Stop Automatisk Musefælde – flerfangstfælde i galvaniseret stål til levende fangst af mus Fang flere mus effektivt – uden brug af gift Har du problemer med mus i hjemmet, lageret eller ",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 179,
    variants: [],
  },
  {
    slug: "pest-stop-fingersikker",
    name: "Pest-Stop Fingersikker",
    sku: "2457",
    price: 69.95,
    regular: 69.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "pest-stop-fingersikker.jpg",
    blurb: "Pest-Stop Fingersikker – sikker smækfælde mod mus Effektiv og sikker bekæmpelse af mus Har du problemer med mus i hjemmet, garagen eller virksomheden – men ønsker en løsning der er mere sikk",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 69.95,
    variants: [],
  },
  {
    slug: "pest-stop-flerfangstfaelde-mus",
    name: "Pest-Stop Flerfangstfælde",
    sku: "2417",
    price: 129.95,
    regular: 129.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "pest-stop-flerfangstfaelde-mus.jpg",
    blurb: "Pest-Stop Flerfangstfælde – effektiv flerfangstfælde til mus Fang flere mus effektivt – uden brugen af gift Har du problemer med mus i hjemmet, på loftet eller i haven? Pest-Stop Flerfangstf",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 129.95,
    variants: [],
  },
  {
    slug: "pest-stop-musegift",
    name: "Pest-Stop Musegift",
    sku: "2082",
    price: 79.95,
    regular: 79.95,
    sale: null,
    inStock: false,
    pest: "mus",
    form: "Gift",
    img: "pest-stop-musegift.jpg",
    blurb: "Pest-Stop Musegift indeholder alphachloralose hvilket hurtigt og effektivt lader musen sove ind. Giften har en ekstremt hurtig effekt. Indpakningen indeholder 2 klar til brug musegiftstation",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 79.95,
    variants: [],
  },
  {
    slug: "pest-stop-musegiftstation",
    name: "Pest-Stop Musegiftstation",
    sku: "2405",
    price: 29.95,
    regular: 29.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "pest-stop-musegiftstation.jpg",
    blurb: "Pest-Stop Musegiftstation – sikker og diskret giftstation til bekæmpelse af mus Effektiv musebekæmpelse med fokus på sikkerhed Har du problemer med mus i hjemmet, garagen eller omkring bygni",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 29.95,
    variants: [],
  },
  {
    slug: "powercat",
    name: "PowerCat smækfælde",
    sku: "100651",
    price: 49.95,
    regular: 49.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "powercat.webp",
    blurb: "PowerCat er udstyret med spidse \"tænder\" samt en meget kraftig smækfunktion der gør fælden særdeles effektiv. Produktet bruges målrettet efter den konkrete opgave og den medfølgende anvisnin",
    brand: "Trinol",
    size: "PowerCat Mus 2stk",
    unit: "24,98 kr./stk.",
    unitValue: 24.975,
    priceMax: 49.95,
    variants: [
      { label: "PowerCat Mus 2stk", sku: "100651", price: 49.95, inStock: true, amount: 2, amountUnit: "stk", isConcentrate: false },
      { label: "PowerCat rotte 1stk", sku: "100691", price: 49.95, inStock: true, amount: 1, amountUnit: "stk", isConcentrate: false },
    ],
  },
  {
    slug: "protecta-evo-ambush",
    name: "Protecta EVO Ambush",
    sku: "",
    price: 10,
    regular: 10,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "protecta-evo-ambush.jpg",
    blurb: "Protecta EVO Ambush – professionel og diskret rottegiftstation til sikker gnaverbekæmpelse Robust giftstation til effektiv kontrol af rotter og mus Protecta EVO Ambush er en professionel gif",
    brand: "Protecta",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 159.95,
    variants: [
      { label: "Nøgle til Protecta rottestationer", sku: "", price: 10, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Protecta EVO Ambush", sku: "170826", price: 159.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "protecta-evo-express",
    name: "Protecta EVO Express",
    sku: "",
    price: 12.95,
    regular: 12.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "protecta-evo-express.jpg",
    blurb: "Protecta EVO Express – professionel rottegiftstation til rotter og mus Sikker og effektiv gnaverbekæmpelse med professionel EVO-teknologi Protecta EVO Express er en robust og manipulationssi",
    brand: "Protecta",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 249.95,
    variants: [
      { label: "Nøgle til Protecta rottestationer", sku: "", price: 12.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Protecta EVO Express", sku: "170836", price: 249.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "provoke-lokkemiddel",
    name: "Provoke lokkemiddel",
    sku: "102501",
    price: 249.95,
    regular: 249.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Lokkemiddel",
    img: "provoke-lokkemiddel.webp",
    blurb: "Provoke – professionelt lokkemiddel til mus og rotter Øg effektiviteten af fælder mod mus og rotter Har du problemer med mus eller rotter, men oplever at de ikke går i fælderne? Provoke er e",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 249.95,
    variants: [],
  },
  {
    slug: "quick-snap-proff",
    name: "QuickSnap proff smækfælde",
    sku: "",
    price: 34.95,
    regular: 34.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "quick-snap-proff.jpg",
    blurb: "QuickSnap Proff Smækfælde – effektiv fælde til mus og rotter Hurtig og sikker bekæmpelse af mus og rotter Har du problemer med mus eller rotter i hjemmet, garagen eller på arbejdspladsen? Qu",
    brand: "Pelsis",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 39.95,
    variants: [
      { label: "Musesmækfælde", sku: "", price: 34.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Rottesmækfælde", sku: "2157", price: 39.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "roban-gold",
    name: "Roban Gold",
    sku: "2029",
    price: 229,
    regular: 229,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Overvågning",
    img: "roban-gold.jpg",
    blurb: "Roban Gold – effektiv overvågning af rotter og mus uden gift Få kontrol over gnaveraktivitet med professionel monitorering Har du mistanke om rotter eller mus, men ønsker at overvåge aktivit",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 229,
    variants: [],
  },
  {
    slug: "rodentlure",
    name: "Rodentlure",
    sku: "1101007600",
    price: 79,
    regular: 79,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Lokkemiddel",
    img: "rodentlure.jpg",
    blurb: "Rodentlure er et professionelt lokkemiddel til rotter og mus, udviklet til effektivt at tiltrække selv sky gnavere. Produktet er baseret på en aromatisk blanding af fødevaregodkendte materia",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 79,
    variants: [],
  },
  {
    slug: "rottegiftstation-galvaniseret",
    name: "Rottegiftstation galvaniseret m/plastlås",
    sku: "170812",
    price: 9,
    regular: 9,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "rottegiftstation-galvaniseret.jpg",
    blurb: "Rottegiftstation galvaniseret m/plastlås – sikker og robust station til bekæmpelse af rotter Effektiv og sikker løsning mod rotter Har du problemer med rotter omkring huset, i udhuset eller ",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 199.95,
    variants: [
      { label: "Advarsels etikette", sku: "170812", price: 9, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Giftspyd", sku: "2115", price: 29, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Lang gul nøgle", sku: "2127", price: 59.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Metal nøgle", sku: "2128", price: 99.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Rottegiftstation galv. m/plastlås", sku: "2126", price: 199.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "tilo-smaekfaelde",
    name: "Tilo smækfælde",
    sku: "",
    price: 39.95,
    regular: 39.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "tilo-smaekfaelde.webp",
    blurb: "Tilo Smækfælde – klassisk og effektiv fælde til mus og rotter Hurtig og direkte bekæmpelse af mus og rotter Har du problemer med mus eller rotter i hjemmet, skuret eller på arbejdspladsen? T",
    brand: "Trinol",
    size: "Musesmækfælde 1stk",
    unit: "39,95 kr./stk.",
    unitValue: 39.95,
    priceMax: 49.95,
    variants: [
      { label: "Musesmækfælde 1stk", sku: "", price: 39.95, inStock: true, amount: 1, amountUnit: "stk", isConcentrate: false },
      { label: "Rottesmækfælde Proff", sku: "170849", price: 49.95, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "tin-catch-flerfangstfaelde",
    name: "Tin Catch flerfangstfælde",
    sku: "140412",
    price: 129.95,
    regular: 129.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "tin-catch-flerfangstfaelde.jpg",
    blurb: "Tin Catch Flerfangstfælde – effektiv flerfangstfælde til levende fangst af mus Fang flere mus effektivt – uden brug af gift Har du problemer med mus i hjemmet, på loftet eller i haven? Tin C",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 129.95,
    variants: [],
  },
  {
    slug: "t-rex-rotte-og-musesmaekfaelde",
    name: "Trapper T-Rex Smækfælde",
    sku: "",
    price: 59.95,
    regular: 59.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "t-rex-rotte-og-musesmaekfaelde.webp",
    blurb: "Trapper T-Rex Smækfælde – professionel fælde til mus og rotter Kraftig og effektiv bekæmpelse af gnavere uden brug af gift Har du problemer med mus eller rotter i hjemmet? Trapper T-Rex Smæk",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 59.95,
    variants: [],
  },
  {
    slug: "trinol-alfa-lokkestation",
    name: "Trinol Alfa lokkestation",
    sku: "100590",
    price: 79,
    regular: 79,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "trinol-alfa-lokkestation.jpg",
    blurb: "Trinol Alfa Lokkestation – sikker giftstation til rotter og mus Fleksibel og sikker løsning til effektiv gnaverbekæmpelse Trinol Alfa Lokkestation er en robust og brugervenlig plast giftstat",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 99,
    variants: [
      { label: "Alfa Rottestation ekls fælde", sku: "100590", price: 79, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Alfa Rottestation inkl fælde", sku: "100591", price: 99, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "trinol-giftstation",
    name: "Trinol Giftstation i blik",
    sku: "140326",
    price: 149.95,
    regular: 149.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "trinol-giftstation.webp",
    blurb: "Trinol Giftstation i blik – robust og sikker giftstation til mus og rotter Sikker udlægning af lokkemiddel mod mus og rotter Har du problemer med mus eller rotter omkring huset, i garagen el",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 179.95,
    variants: [
      { label: "Musegiftstation", sku: "140326", price: 149.95, inStock: false, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Rottegiftstation", sku: "170800", price: 179.95, inStock: false, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "trinol-multikill-musefaelde",
    name: "Trinol MultiKill musefælde",
    sku: "140413",
    price: 899.95,
    regular: 899.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "trinol-multikill-musefaelde.jpg",
    blurb: "Trinol MultiKill musefælde er en avanceret, automatisk elektronisk musefælde med multi-kill funktion, der kan bekæmpe op til 10 mus pr. opsætning uden behov for manuel nulstilling. Fælden er",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 899.95,
    variants: [],
  },
  {
    slug: "trinol-elektronisk-musefaelde",
    name: "Trinol elektronisk musefælde",
    sku: "140410",
    price: 299,
    regular: 299,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "trinol-elektronisk-musefaelde.jpg",
    blurb: "Trinol elektronisk musefælde er en effektiv og moderne løsning til hurtig og human bekæmpelse af mus. Fælden anvender et kraftigt elektrisk stød, som afliver musen øjeblikkeligt, hvilket sik",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 299,
    variants: [],
  },
  {
    slug: "trinol-muselokkeboks",
    name: "Trinol muselokkeboks",
    sku: "100602",
    price: 29,
    regular: 29,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Gift",
    img: "trinol-muselokkeboks.jpg",
    blurb: "Trinol Muselokkeboks – sikker og diskret giftstation til bekæmpelse af mus Effektiv og sikker løsning mod mus i hjem og bygninger Har du problemer med mus i garage, skur, loft eller langs hu",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 29,
    variants: [],
  },
  {
    slug: "trinol-traesmaekfaelde",
    name: "Trinol træsmækfælde",
    sku: "100693",
    price: 24,
    regular: 24,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "trinol-traesmaekfaelde.jpg",
    blurb: "Trinol træsmækfælde er en klassisk og kraftfuld løsning til effektiv bekæmpelse af både mus og rotter. Fælden er fremstillet i træ med en stærk metalmekanisme, der sikrer hurtig og præcis fa",
    brand: "Trinol",
    size: "Rottesmækfælde 1stk",
    unit: "24,00 kr./stk.",
    unitValue: 24,
    priceMax: 29,
    variants: [
      { label: "Rottesmækfælde 1stk", sku: "100693", price: 24, inStock: true, amount: 1, amountUnit: "stk", isConcentrate: false },
      { label: "Musesmækfælde 2stk", sku: "100684", price: 29, inStock: true, amount: 2, amountUnit: "stk", isConcentrate: false },
    ],
  },
  {
    slug: "victor-elektronisk-musefaelde",
    name: "Victor Elektronisk Musefælde",
    sku: "140425",
    price: 299.95,
    regular: 299.95,
    sale: null,
    inStock: true,
    pest: "mus",
    form: "Fælde",
    img: "victor-elektronisk-musefaelde.jpg",
    blurb: "Victor Elektronisk Musefælde – hurtig og hygiejnisk bekæmpelse af mus uden gift Effektiv elektronisk løsning mod mus i hjemmet Har du problemer med mus i hjemmet, på loftet eller i garagen? ",
    brand: "Victor",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 299.95,
    variants: [],
  },
  {
    slug: "advion-ant-gel",
    name: "Advion Ant Gel",
    sku: "",
    price: 799,
    regular: 799,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Gel",
    img: "advion-ant-gel.jpg",
    blurb: "Advion Ant Gel – Professionel myregel med indoxacarb til effektiv bekæmpelse af myrer Avanceret gel mod faraomyrer, sorte myrer og andre problematiske myrearter – bekæmper kolonien indefra A",
    brand: "",
    size: "1x30g",
    unit: "2663,33 kr./100 g",
    unitValue: 2663.33,
    priceMax: 2999,
    variants: [
      { label: "1x30g", sku: "", price: 799, inStock: true, amount: 30, amountUnit: "g", isConcentrate: false },
      { label: "2x30g", sku: "", price: 1499, inStock: true, amount: 60, amountUnit: "g", isConcentrate: false },
      { label: "4x30g", sku: "110268", price: 2999, inStock: true, amount: 120, amountUnit: "g", isConcentrate: false },
    ],
  },
  {
    slug: "bug-bar-tom-myrelokkedaase",
    name: "Bug bar TOM myrelokkedåse",
    sku: "110277",
    price: 15,
    regular: 15,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Gel",
    img: "bug-bar-tom-myrelokkedaase.jpg",
    blurb: "Bug Bar TOM Myrelokkedåse – Professionel tom lokkestation til gel og lokkemidler Lav din egen diskrete myrelokkedåse til målrettet bekæmpelse af myrer, sølvfisk og skægkræ Derfor vælger vore",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 15,
    variants: [],
  },
  {
    slug: "forlaenger-til-bait-gun",
    name: "Forlænger til Bait Gun",
    sku: "119484",
    price: 1299,
    regular: 1299,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Gel",
    img: "forlaenger-til-bait-gun.webp",
    blurb: "Forlænger til Bait Gun 50 cm er et professionelt tilbehør, der gør udlægning af gelprodukter som Maxforce, Advion og Goliath både nemmere, hurtigere og mere præcis. Med en længde på 50 cm få",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 1299,
    variants: [],
  },
  {
    slug: "imidasect-ants",
    name: "Imidasect Ants",
    sku: "",
    price: 449,
    regular: 449,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Gel",
    img: "imidasect-ants.jpg",
    blurb: "Imidasect Ants – Professionel sirupbaseret myregel til langtidsholdbar bekæmpelse Effektiv lokkemadsbehandling mod myrer og myrebo – udviklet til målrettet professionel anvendelse Imidasect ",
    brand: "",
    size: "1x30g",
    unit: "1496,67 kr./100 g",
    unitValue: 1496.67,
    priceMax: 2599,
    variants: [
      { label: "1x30g", sku: "", price: 449, inStock: true, amount: 30, amountUnit: "g", isConcentrate: false },
      { label: "2x30g", sku: "", price: 889, inStock: true, amount: 60, amountUnit: "g", isConcentrate: false },
      { label: "4x30g", sku: "", price: 1699, inStock: true, amount: 120, amountUnit: "g", isConcentrate: false },
      { label: "6x30g", sku: "110311", price: 2599, inStock: true, amount: 180, amountUnit: "g", isConcentrate: false },
    ],
  },
  {
    slug: "maxforce-q-myrelokkedaase",
    name: "Maxforce Q Myrelokkedåse",
    sku: "110275",
    price: 49,
    regular: 49,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Station",
    img: "maxforce-q-myrelokkedaase.webp",
    blurb: "Maxforce Q Myrelokkedåse – Effektiv myrelokkedåse til bekæmpelse af myrer indendørs Diskret myrelokkedåse der bekæmper myrer ved kilden – ikke kun de synlige myrer Maxforce Q Myrelokkedåse e",
    brand: "ENVU",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 49,
    variants: [],
  },
  {
    slug: "maxforce-quantum",
    name: "Maxforce Quantum",
    sku: "110271-1",
    price: 949,
    regular: 949,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Gel",
    img: "maxforce-quantum.jpg",
    blurb: "Maxforce Quantum – Professionel myregift indendørs mod faraomyrer og sorte havemyrer Sirupbaseret myremiddel til målrettet bekæmpelse direkte i kolonien Professionel myregift indendørs kræve",
    brand: "ENVU",
    size: "1x30g",
    unit: "3163,33 kr./100 g",
    unitValue: 3163.33,
    priceMax: 3649,
    variants: [
      { label: "1x30g", sku: "110271-1", price: 949, inStock: true, amount: 30, amountUnit: "g", isConcentrate: false },
      { label: "2x30g", sku: "", price: 1849, inStock: true, amount: 60, amountUnit: "g", isConcentrate: false },
      { label: "4x30g", sku: "110271", price: 3649, inStock: true, amount: 120, amountUnit: "g", isConcentrate: false },
    ],
  },
  {
    slug: "myreudvanding-xtra",
    name: "Myreudvanding Xtra",
    sku: "3130",
    price: 1099.95,
    regular: 1099.95,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Pulver",
    img: "myreudvanding-xtra.jpg",
    blurb: "Myreudvanding Xtra er et letopløseligt middel til effektiv bekæmpelse af myrer udendørs . Produktet blandes med vand og udvandes direkte dér, hvor myrerne kommer op, ved myrebo, langs soklen",
    brand: "Pelsis",
    size: "2kg",
    unit: "55,00 kr./100 g",
    unitValue: 54.9975,
    priceMax: 4999.95,
    variants: [
      { label: "2kg", sku: "3130", price: 1099.95, inStock: true, amount: 2, amountUnit: "kg", isConcentrate: false },
      { label: "10kg", sku: "3131", price: 4999.95, inStock: true, amount: 10, amountUnit: "kg", isConcentrate: false },
    ],
  },
  {
    slug: "ps-myre-gel-10g",
    name: "PS Myre-gel 10g",
    sku: "",
    price: 89,
    regular: 89,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Gel",
    img: "ps-myre-gel-10g.jpg",
    blurb: "PS Myre-gel 10g er et effektivt insektmiddel til målrettet bekæmpelse af myrer indendørs. Gelen er udviklet til brug i revner, sprækker og skjulesteder, hvor myrer typisk færdes. Produktet v",
    brand: "Pest-Stop",
    size: "10 g",
    unit: "890,00 kr./100 g",
    unitValue: 0,
    priceMax: 89,
    variants: [],
  },
  {
    slug: "ps-myrelokkedaase",
    name: "PS Myrelokkedåse",
    sku: "",
    price: 119.95,
    regular: 119.95,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Station",
    img: "ps-myrelokkedaase.jpg",
    blurb: "PS Myrelokkedåse er en klassisk og effektiv løsning til bekæmpelse af myrer i og omkring hjemmet. Produktet er udviklet til målrettet bekæmpelse dér, hvor myrerne generer – både indendørs og",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 119.95,
    variants: [],
  },
  {
    slug: "tom-myrelokkedaase",
    name: "Tom Myrelokkedåse",
    sku: "130783",
    price: 9,
    regular: 9,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Station",
    img: "tom-myrelokkedaase.webp",
    blurb: "Tom Myrelokkedåse er en praktisk og genanvendelig lokkedåse, der gør det nemt at udlægge gelprodukter mod myrer og skægkræ på en sikker og professionel måde. Lokkedåsen leveres uden indhold ",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 9,
    variants: [],
  },
  {
    slug: "trinol-myrestop",
    name: "Trinol MyreStop",
    sku: "110069",
    price: 129,
    regular: 129,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Pulver",
    img: "trinol-myrestop.webp",
    blurb: "Trinol MyreStop – Effektivt pulver mod myrebo Målrettet bekæmpelse af myrer med effektivt pulver Trinol MyreStop er et effektivt insektmiddel i granulatform udviklet til bekæmpelse af myrer ",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 129,
    variants: [],
  },
  {
    slug: "trinol-myrelokkedaase",
    name: "Trinol Myrelokkedåse 2stk",
    sku: "100517",
    price: 79.95,
    regular: 79.95,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Station",
    img: "trinol-myrelokkedaase.jpg",
    blurb: "Trinol Myrelokkedåse 2 stk – Effektiv bekæmpelse af sorte havemyrer i og omkring boligen Diskret og klar-til-brug løsning mod myrer – bekæmper boet indefra Trinol Myrelokkedåse er en brugerv",
    brand: "Trinol",
    size: "2 stk",
    unit: "39,98 kr./stk.",
    unitValue: 0,
    priceMax: 79.95,
    variants: [],
  },
  {
    slug: "trinol-myresand",
    name: "Trinol Myresand",
    sku: "100530",
    price: 129.95,
    regular: 129.95,
    sale: null,
    inStock: true,
    pest: "myrer",
    form: "Pulver",
    img: "trinol-myresand.jpg",
    blurb: "Trinol Myresand er en effektiv og giftfri løsning til bekæmpelse af myrer i haven. Produktet består af naturlige ingredienser og virker ved at blokere og forstyrre myrernes gangsystemer. Når",
    brand: "Trinol",
    size: "1ltr",
    unit: "12,99 kr./100 ml",
    unitValue: 12.995,
    priceMax: 499.95,
    variants: [
      { label: "1ltr", sku: "100530", price: 129.95, inStock: true, amount: 1, amountUnit: "l", isConcentrate: false },
      { label: "5ltr", sku: "100531", price: 499.95, inStock: true, amount: 5, amountUnit: "l", isConcentrate: false },
    ],
  },
  {
    slug: "bromablok-pro",
    name: "Bromablok PRO",
    sku: "2027",
    price: 899.95,
    regular: 899.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "bromablok-pro.jpg",
    blurb: "Bromablok PRO er en rød voksblok, som er særdeles attraktiv for og effektiv mod rotter. Midlet er klar til brug og indeholder råvarer i høj kvalitet – bl.a. hvedemel, hakket hvede, samt andr",
    brand: "Pelsis",
    size: "Bromablok Pro 10kg á 200g",
    unit: "9,00 kr./100 g",
    unitValue: 8.9995,
    priceMax: 949.95,
    variants: [
      { label: "Bromablok Pro 10kg á 200g", sku: "2027", price: 899.95, inStock: true, amount: 10, amountUnit: "kg", isConcentrate: false },
      { label: "Bromablok Pro 10kg á 20g", sku: "2025", price: 949.95, inStock: true, amount: 10, amountUnit: "kg", isConcentrate: false },
    ],
  },
  {
    slug: "d3-harmonix-pasta",
    name: "D3 Harmonix Pasta",
    sku: "2075",
    price: 1399.95,
    regular: 1399.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "d3-harmonix-pasta.jpg",
    blurb: "D3 Harmonix Pasta er et nyt og meget effektivt rodenticid uden antikoagulanter! Midlet som er godkendt til bekæmpelse af husrotte, brunrotte samt mus, er sammenlignet med traditionelle roden",
    brand: "ENVU",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 1399.95,
    variants: [],
  },
  {
    slug: "edialux-aptum",
    name: "Edialux Aptum",
    sku: "1101077940",
    price: 149,
    regular: 149,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "edialux-aptum.jpg",
    blurb: "Edialux Aptum er en kompakt og alsidig lokkemadsstation, udviklet til effektiv bekæmpelse og monitorering af gnavere. Den er designet til professionel brug, hvor fleksibilitet, sikkerhed og ",
    brand: "Edialux",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 149,
    variants: [],
  },
  {
    slug: "exittus-blokke",
    name: "Exittus Blokke",
    sku: "102538",
    price: 1699.95,
    regular: 1699.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "exittus-blokke.webp",
    blurb: "Exittus Blokke er et klar til brug, super effektivt bekæmpelsesmiddel mod rotter og mus. Midlet indeholder Cholecalciferol (D-vitamin), og er en velsmagende formel med hurtig accept og en vi",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 1699.95,
    variants: [],
  },
  {
    slug: "generation-mix",
    name: "Generation Mix",
    sku: "1101077910",
    price: 699.95,
    regular: 699.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "generation-mix.jpg",
    blurb: "Generation Mix er et effektivt middel til bekæmpelse af rotter og mus! Midlet sikre stor ædelyst med den nye Multimix-formulering (Havreflager, solsikkefrø, græskarkerner og majs). Ved køb a",
    brand: "Pelsis",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 699.95,
    variants: [],
  },
  {
    slug: "generation-pasta",
    name: "Generation Pasta",
    sku: "118454",
    price: 1199,
    regular: 1199,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "generation-pasta.webp",
    blurb: "Generation Pasta – Professionel musegift og rottegift til autoriserede brugere Generation Pasta er en professionel og yderst effektiv rodenticid udviklet til bekæmpelse af både mus og rotter",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 1199,
    variants: [],
  },
  {
    slug: "klerat-voksblok",
    name: "Klerat Voksblok",
    sku: "102544",
    price: 1899.95,
    regular: 1899.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "klerat-voksblok.webp",
    blurb: "Klerat Voksblok er et effektivt og kraftfuldt 2.generations rottegift, der kan anvendes til bekæmpelse af rotter i og omkring bygninger. Voksblokkene er udviklet til at tage sig af selv de m",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 1899.95,
    variants: [],
  },
  {
    slug: "neo-rottegiftstation",
    name: "NEO Rottegiftstation",
    sku: "2047",
    price: 189,
    regular: 189,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "neo-rottegiftstation.jpg",
    blurb: "NEO Rottegiftstation – sikker og robust station til bekæmpelse af rotter Sikker udlægning af lokkemiddel mod rotter Har du problemer med rotter i huset, i haven eller ved virksomheden? NEO R",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 189,
    variants: [],
  },
  {
    slug: "notrac-blox",
    name: "Notrac Blox",
    sku: "170014",
    price: 1499.95,
    regular: 1499.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "notrac-blox.jpg",
    blurb: "Notrac Blox er et effektivt middel til bekæmpelse af rotter og mus, i og omkring bygninger samt i kloakker. Blokkene indeholder en optimal mængde af fødevarer samt en smule paraffin, hvilket",
    brand: "Pelsis",
    size: "225g Blokke (9kg Karton)",
    unit: "666,64 kr./100 g",
    unitValue: 666.644,
    priceMax: 1499.95,
    variants: [
      { label: "225g Blokke (9kg Karton)", sku: "170014", price: 1499.95, inStock: true, amount: 225, amountUnit: "g", isConcentrate: false },
      { label: "28g Blokke (8kg Spand)", sku: "170015", price: 1499.95, inStock: true, amount: 28, amountUnit: "g", isConcentrate: false },
    ],
  },
  {
    slug: "pest-stop-flerfangstfaelde",
    name: "Pest-Stop Flerfangstfælde",
    sku: "2418",
    price: 179,
    regular: 179,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Fælde",
    img: "pest-stop-flerfangstfaelde.jpg",
    blurb: "Pest-Stop Flerfangstfælde – galvaniseret stålbur til human fangst af flere rotter Effektiv og giftfri løsning ved større rotteangreb Har du problemer med rotter i lager, stald, garage eller ",
    brand: "Pest-Stop",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 179,
    variants: [],
  },
  {
    slug: "protecta-evo-landscape",
    name: "Protecta EVO Landscape",
    sku: "170831",
    price: 12.95,
    regular: 12.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "protecta-evo-landscape.jpg",
    blurb: "Protecta EVO Landscape er en særdeles smart rottegiftstation designet til at kunne bruges i omgivelser med mange gæster / kunder, der helst ikke må se at der bekæmpes mod skadedyr. ✓ Beskytt",
    brand: "Protecta",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 179.95,
    variants: [
      { label: "Ekstra nøgle", sku: "170831", price: 12.95, inStock: false, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Protecta EVO Landscape", sku: "2107", price: 179.95, inStock: false, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "racumin-expert",
    name: "Racumin Expert",
    sku: "1101004007",
    price: 999.95,
    regular: 999.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "racumin-expert.jpg",
    blurb: "Racumin Expert er en meget effektiv og klar til brug, rottegiftspasta mod brune rotter. Pastaen kan f.eks bruges på genbrugspladser og til beskyttelse af infrastruktur som el- eller kommunik",
    brand: "Racumin",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 999.95,
    variants: [],
  },
  {
    slug: "racumin-foam",
    name: "Racumin Foam",
    sku: "2020",
    price: 799.95,
    regular: 799.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "racumin-foam.jpg",
    blurb: "Racumin Foam er et 1. generations antikoagulant rottegift, lavet i en smart skumformulering. Midlet bekæmper brune rotter helt uden lokkemad i og omkring bygninger. Køb af Racumin Foam kræve",
    brand: "Racumin",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 799.95,
    variants: [],
  },
  {
    slug: "t-rex-iq",
    name: "T-rex IQ",
    sku: "170897",
    price: 349,
    regular: 349,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Fælde",
    img: "t-rex-iq.jpg",
    blurb: "T-Rex IQ er en professionel rottefælde, der kombinerer kraftfuld smækfunktion med avanceret Bell IQ sensor teknologi. Fælden registrerer aktivitet og sender data direkte til en app, så du al",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 349,
    variants: [],
  },
  {
    slug: "talon-soft-pasta",
    name: "Talon Soft Pasta",
    sku: "1105000308",
    price: 249.95,
    regular: 249.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "talon-soft-pasta.jpg",
    blurb: "Talon Soft Pasta er effektiv pasta på tube med stor ædelyst. Midlet er bevist effektiv mod resistente gnavere og kun en enkelt fodring er nok til at besejre rotter og mus. Midlet kan nemt og",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 249.95,
    variants: [],
  },
  {
    slug: "tanaco-bromakorn",
    name: "Tanaco Bromakorn",
    sku: "20230",
    price: 349,
    regular: 349,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Gift",
    img: "tanaco-bromakorn.jpg",
    blurb: "Tanaco Bromakorn – effektiv rotte- og musebekæmpelse med hele korn Professionelt lokkemiddel til bekæmpelse af rotter og mus Tanaco Bromakorn er et kraftigt og effektivt kornbaseret bekæmpel",
    brand: "Pelsis",
    size: "Bromakorn Pro 10kg (hele)",
    unit: "3,49 kr./100 g",
    unitValue: 3.49,
    priceMax: 449,
    variants: [
      { label: "Bromakorn Pro 10kg (hele)", sku: "20230", price: 349, inStock: true, amount: 10, amountUnit: "kg", isConcentrate: false },
      { label: "Bromakorn 12kg á 100g", sku: "2009", price: 449, inStock: true, amount: 12, amountUnit: "kg", isConcentrate: false },
    ],
  },
  {
    slug: "trap-in-a-box",
    name: "Trap-in-a-box",
    sku: "2152",
    price: 99,
    regular: 99,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Fælde",
    img: "trap-in-a-box.jpg",
    blurb: "Trap-in-a-Box – sikker og diskret rottefælde i lukket kasse Effektiv rottebekæmpelse med fokus på sikkerhed Har du problemer med rotter omkring huset, i haven, stalden eller ved virksomheden",
    brand: "Pelsis",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 99,
    variants: [],
  },
  {
    slug: "trinol-elektronisk-rottefaelde",
    name: "Trinol Elektronisk rottefælde",
    sku: "140411",
    price: 429,
    regular: 429,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Fælde",
    img: "trinol-elektronisk-rottefaelde.jpg",
    blurb: "Trinol elektronisk rottefælde er en moderne og effektiv løsning til hurtig og human bekæmpelse af rotter. Fælden anvender et kraftigt elektrisk stød, som dræber rotten øjeblikkeligt, hvilket",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 429,
    variants: [],
  },
  {
    slug: "trinol-raptor-smaekfaelde",
    name: "Trinol Raptor Smækfælde",
    sku: "170842",
    price: 49,
    regular: 49,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Fælde",
    img: "trinol-raptor-smaekfaelde.jpg",
    blurb: "Trinol Raptor smækfælde er en kraftig og professionel rottesmækfælde, udviklet til effektiv bekæmpelse af rotter uden brug af gift. Fælden er designet til at passe i de fleste rottefoderstat",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 69,
    variants: [
      { label: "Raptor Smækfælde", sku: "170842", price: 49, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Raptor Smækfælde inkl cover", sku: "170841", price: 69, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
  {
    slug: "victor-elektronisk-rottefaelde",
    name: "Victor elektronisk rottefælde",
    sku: "140428",
    price: 599.95,
    regular: 599.95,
    sale: null,
    inStock: true,
    pest: "rotter",
    form: "Fælde",
    img: "victor-elektronisk-rottefaelde.jpg",
    blurb: "Victor Elektronisk Rottefælde – hurtig og effektiv bekæmpelse af rotter uden gift Moderne løsning mod rotter med høj effektivitet Har du problemer med rotter i hjemmet, skuret eller virksomh",
    brand: "Victor",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 599.95,
    variants: [],
  },
  {
    slug: "ironmax-pro",
    name: "IronMax Pro",
    sku: "",
    price: 159.95,
    regular: 159.95,
    sale: null,
    inStock: true,
    pest: "snegle",
    form: "Andet",
    img: "ironmax-pro.jpg",
    blurb: "IronMax Pro er et effektiv og ufarligt bekæmpelsesmiddel mod dræbersnegle, agersnegle og skovsnegle i spiselige og ikke spiselige afgrøder i havebrug, landbrug og væksthuse. 1-2 IronMax korn",
    brand: "",
    size: "500g",
    unit: "31,99 kr./100 g",
    unitValue: 31.99,
    priceMax: 1999.95,
    variants: [
      { label: "500g", sku: "", price: 159.95, inStock: true, amount: 500, amountUnit: "g", isConcentrate: false },
      { label: "1kg", sku: "", price: 269.95, inStock: true, amount: 1, amountUnit: "kg", isConcentrate: false },
      { label: "5kg", sku: "", price: 999.95, inStock: true, amount: 5, amountUnit: "kg", isConcentrate: false },
      { label: "20kg", sku: "", price: 1999.95, inStock: true, amount: 20, amountUnit: "kg", isConcentrate: false },
    ],
  },
  {
    slug: "sluxx-hp-20kg",
    name: "Sluxx HP 20kg",
    sku: "19337",
    price: 1999.95,
    regular: 1999.95,
    sale: null,
    inStock: true,
    pest: "snegle",
    form: "Andet",
    img: "sluxx-hp-20kg.jpg",
    blurb: "Sluxx HP 20kg – professionelt sneglemiddel mod agersnegle og skovsnegle Effektiv bekæmpelse af snegle i landbrug, haver og væksthuse Har du problemer med agersnegle eller skovsnegle i afgrød",
    brand: "",
    size: "20 kg",
    unit: "10,00 kr./100 g",
    unitValue: 0,
    priceMax: 1999.95,
    variants: [],
  },
  {
    slug: "trinol-ferroslug",
    name: "Trinol FerroSlug",
    sku: "100904",
    price: 89,
    regular: 89,
    sale: null,
    inStock: true,
    pest: "snegle",
    form: "Andet",
    img: "trinol-ferroslug.jpg",
    blurb: "Trinol FerroSlug – Effektivt sneglemiddel til have og drivhus Brugsklart lokkemiddel mod agersnegle og skovsnegle – godkendt til økologisk dyrkning Trinol FerroSlug er et effektivt og bruger",
    brand: "Trinol",
    size: "500g",
    unit: "17,80 kr./100 g",
    unitValue: 17.8,
    priceMax: 149,
    variants: [
      { label: "500g", sku: "100904", price: 89, inStock: true, amount: 500, amountUnit: "g", isConcentrate: false },
      { label: "1kg", sku: "100906", price: 149, inStock: true, amount: 1, amountUnit: "kg", isConcentrate: false },
    ],
  },
  {
    slug: "trinol-sneglefaelde",
    name: "Trinol Sneglefælde",
    sku: "130249",
    price: 79,
    regular: 79,
    sale: null,
    inStock: true,
    pest: "snegle",
    form: "Fælde",
    img: "trinol-sneglefaelde.webp",
    blurb: "Trinol Sneglefælde – diskret og effektiv kontrol af snegle i haven Snegle kan hurtigt blive et stort problem i haven, især i fugtige perioder hvor de angriber planter, grøntsager og blomster",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 79,
    variants: [],
  },
  {
    slug: "climbup-vaeggelusfaelde",
    name: "ClimbUp Væggelusfælde",
    sku: "160049",
    price: 59,
    regular: 59,
    sale: null,
    inStock: true,
    pest: "vaeggelus",
    form: "Overvågning",
    img: "climbup-vaeggelusfaelde.jpg",
    blurb: "ClimbUp Væggelusfælde – Effektiv monitorering og tidlig opdagelse af væggelus Opdag væggelus i tide med en professionel monitoreringsfælde ClimbUp Væggelusfælde er en smart og diskret løsnin",
    brand: "",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 59,
    variants: [],
  },
  {
    slug: "trinol-bed-bug-barrier",
    name: "Trinol Bed Bug Barrier",
    sku: "125574",
    price: 49,
    regular: 49,
    sale: null,
    inStock: true,
    pest: "vaeggelus",
    form: "Overvågning",
    img: "trinol-bed-bug-barrier.webp",
    blurb: "Trinol Bed Bug Barrier er en effektiv og giftfri løsning til at opdage og fange væggelus. Fælden placeres typisk under sengeben, hvor væggelus naturligt bevæger sig, og fungerer som både mon",
    brand: "Trinol",
    size: "",
    unit: "",
    unitValue: 0,
    priceMax: 49,
    variants: [
      { label: "Hvid", sku: "125574", price: 49, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
      { label: "Sort", sku: "125979", price: 49, inStock: true, amount: 0, amountUnit: "", isConcentrate: false },
    ],
  },
];

export const BY_SLUG = new Map(PRODUCTS.map((p) => [p.slug, p]));

/** De skadedyr, der faktisk har varer, med antal. Bruges i browseren. */
export const PEST_COUNTS = PRODUCTS.reduce<Record<string, number>>((acc, p) => {
  acc[p.pest] = (acc[p.pest] ?? 0) + 1;
  return acc;
}, {});

export const FORMS = [...new Set(PRODUCTS.map((p) => p.form))].sort();

/** Mærkerne, der faktisk optræder. Baymard: mærke er et af de filtre,
    folk leder efter, og 51 % af butikker mangler det. */
export const BRANDS = [...new Set(PRODUCTS.map((p) => p.brand).filter(Boolean))].sort();

export function dkr(n: number): string {
  return n.toLocaleString("da-DK") + " kr.";
}

/** Fire varer har ingen pris i hans katalog. "0 kr." ville laeses som
    gratis, saa de faar en pris paa foresporgsel i stedet. */
export function hasPrice(p: Product): boolean {
  return p.price > 0;
}

/** Fås varen i flere størrelser til forskellig pris? */
export function hasRange(p: Product): boolean {
  return p.variants.length > 1 && p.priceMax > p.price;
}

/** Et ægte tilbud, ikke bare et flag. */
export function isDeal(p: Product): boolean {
  return p.sale != null && p.sale < p.regular;
}
